// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtYnQdHOPQMLL5zGuJ2vPxddmOrWodX7M',
    appId: '1:624285930553:web:9b02c8788959399a4669e8',
    messagingSenderId: '624285930553',
    projectId: 'wishlink-5040f',
    authDomain: 'wishlink-5040f.firebaseapp.com',
    storageBucket: 'wishlink-5040f.firebasestorage.app',
    measurementId: 'G-MF9BQHCJHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCz21F17_W_t7jKW2_XIzm_oMCgYhFeY',
    appId: '1:624285930553:android:74302ae0ae5680614669e8',
    messagingSenderId: '624285930553',
    projectId: 'wishlink-5040f',
    storageBucket: 'wishlink-5040f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Jwz_JC6F5ZmrfGdJm8rvIi-V4VV6tbQ',
    appId: '1:624285930553:ios:056c1fef7ef31ed34669e8',
    messagingSenderId: '624285930553',
    projectId: 'wishlink-5040f',
    storageBucket: 'wishlink-5040f.firebasestorage.app',
    iosBundleId: 'com.example.wishlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Jwz_JC6F5ZmrfGdJm8rvIi-V4VV6tbQ',
    appId: '1:624285930553:ios:056c1fef7ef31ed34669e8',
    messagingSenderId: '624285930553',
    projectId: 'wishlink-5040f',
    storageBucket: 'wishlink-5040f.firebasestorage.app',
    iosBundleId: 'com.example.wishlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtYnQdHOPQMLL5zGuJ2vPxddmOrWodX7M',
    appId: '1:624285930553:web:643a2a644bf2b6a94669e8',
    messagingSenderId: '624285930553',
    projectId: 'wishlink-5040f',
    authDomain: 'wishlink-5040f.firebaseapp.com',
    storageBucket: 'wishlink-5040f.firebasestorage.app',
    measurementId: 'G-6KBDKDNGDC',
  );
}
